CI CD workflow file created'

diff --git a/.github/workflows/CI CD.yaml b/.github/workflows/CI CD.yaml
--- a/.github/workflows/CI CD.yaml
+++ b/.github/workflows/CI CD.yaml
@@ -10,10 +10,9 @@ name: My Test Workflow (Skyu Generated)
 env:
   ENCODED_PIPELINE_SECRET: >-
     ${{secrets.TESTSERVICE2_ENV_D257AF4E9409415F974CFDD70A2A25DF_APP_0666FAC591E24B38A5C3176884514379_CICD}}
-  IMAGE_NAME: iwiick-test-image:latest
-  IMAGE_NAME_TO_PUSH: iwiick-test-image.latest
-  DOCKER_FILE_NAME: sample.Dockerfile
-  DOCKER_FILE_PATH: /src
+  REPOSITORY_NAME: iwiick
+  RANDOM_ENV_VALUE: HAHAHAHAHA
+  TEST_ENV_WITH_SECRET_VAL: ${{secrets.DOCKER_IMAGE_NAME}}
 jobs:
   build:
     permissions: write-all
@@ -32,3 +31,26 @@ jobs:
         run: >-
           docker images && docker build -t ${{ env.IMAGE_NAME }} -f
           ${{env.DOCKER_FILE_NAME}} .${{env.DOCKER_FILE_PATH}} && docker images
+      - name: 'Run :: Configure AWS credentials'
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ env.roleARN }}
+          role-session-name: skyu-pipeline-assume-role-session
+          aws-region: ${{ env.region }}
+      - name: 'Run :: Login to Amazon ECR'
+        id: skyu-login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+      - name: 'Run :: Deploy and Notify Resource Service'
+        run: |2-
+
+              response=$(curl -sS -w "%{http_code}" -d "imageRegistryURL=${{ steps.skyu-login-ecr.outputs.registry }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.IMAGE_NAME_TO_PUSH }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&commitDetails[commitHash]=${{ github.event.after }}&commitDetails[commitAvatar]=https://github.com/${{ github.event.head_commit.author.name }}.png&commitDetails[commitTime]=${{ github.event.head_commit.timestamp }}&commitDetails[commitMessage]=\"${{ github.event.head_commit.message }}\"&commitDetails[commitUser]=${{ github.event.head_commit.author.name }}" -X PATCH -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.DEPLOYMENT_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.DEPLOYMENT_PROJECT_ID }}' -H 'x-environment-id: ${{ env.DEPLOYMENT_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.DEPLOYMENT_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded' 'https://api.dev.skyu.io/resource-service/applications/deploy')
+              
+              if [ $response -ne 200 ]; then
+                echo "HTTP status code is not 200. Exiting with failure."
+                exit 1
+              fi
+            
+      - name: 'Run :: My Custom Step'
+        run: >-
+          echo " Pipeline service works yall!.
+          $\{\{secrets.DOCKER_IMAGE_NAME\}\} and $\{\{env.RANDOM_ENV_VALUE\}\}"
