container-dev_env_860207ab-32d0-4ad2-8b78-e569ac242760_app_d42bb57b-ef7e-48b4-addb-f7600888bb4a workflow file created'

diff --git a/.github/workflows/container-dev_env_860207ab-32d0-4ad2-8b78-e569ac242760_app_d42bb57b-ef7e-48b4-addb-f7600888bb4a.yaml b/.github/workflows/container-dev_env_860207ab-32d0-4ad2-8b78-e569ac242760_app_d42bb57b-ef7e-48b4-addb-f7600888bb4a.yaml
--- a/.github/workflows/container-dev_env_860207ab-32d0-4ad2-8b78-e569ac242760_app_d42bb57b-ef7e-48b4-addb-f7600888bb4a.yaml
+++ b/.github/workflows/container-dev_env_860207ab-32d0-4ad2-8b78-e569ac242760_app_d42bb57b-ef7e-48b4-addb-f7600888bb4a.yaml
@@ -7,7 +7,7 @@ name: >-
       - master
   workflow_dispatch: {}
   repository_dispatch:
-    types: pipeline_a4313685-38db-44d4-a32d-0557d47c177d
+    types: pipeline_aa0bfc2a-1ab3-45a4-9bac-e6dd52beed9e
 env:
   ENCODED_PIPELINE_SECRET: >-
     ${{secrets.TESTSERVICE2_ENV_860207AB32D04AD28B78E569AC242760_APP_D42BB57BEF7E48B4ADDBF7600888BB4A_CONTAINERDEV_ENV_860207AB32D04AD28B78E569AC242760_APP_D42BB57BEF7E48B4ADDBF7600888BB4A}}
@@ -15,7 +15,7 @@ env:
   IMAGE_NAME: skyu-gen-img
   DOCKER_FILE_PATH: Dockerfile
   DOCKER_BUILD_CONTEXT: .
-  SCAN_SEVERITY: HIGH
+  SCAN_SEVERITY: CRITICAL
   TRIVY_SCAN_EXIT_CODE: '1'
   TRIVY_RESULT_FORMAT: json
   REPOSITORY_NAME: iwiick
@@ -78,6 +78,24 @@ jobs:
           vuln-type: os,library
           severity: ${{env.SCAN_SEVERITY}}
         if: ${{ env.IMAGE_EXISTS_IN_ECR == 'false' }}
+      - name: 'Run :: Upload Trivy Result To S3'
+        run: |2-
+
+              response=$(curl -X POST https://api.dev.skyu.io/file-service -H "x-organization-id: ${{ env.DEPLOYMENT_ORGANIZATION_ID }}" -H "x-project-id: ${{ env.DEPLOYMENT_PROJECT_ID }}" -H "x-environment-id: ${{ env.DEPLOYMENT_ENVIRONMENT_ID }}" -H "x-resource-id: trivy_${{ env.IMAGE_TAG }}" -H "Content-Type: multipart/form-data" -F "file=@trivy-results.json" -F "provider=aws" -F "resourceType=trivy-report" -F "cloudStoragePath=/${{ env.DEPLOYMENT_APPLICATION_ID }}/${{ env.IMAGE_TAG }}" -F "metadata={"scanServerity": "${{env.SCAN_SEVERITY}}"}")
+              status_code=$?
+
+              if [ $status_code -eq 0 ]; then
+                if echo "$response" | grep -q '"success":true'; then
+                  echo "SUCCESS :: $response"
+                else
+                  echo "FAILED :: $response"
+                  exit 1
+                fi
+              else
+                echo "Failed to upload Trivy Result to S3. HTTP status code: $status_code"
+                exit 1
+              fi
+              
       - name: 'Run :: Create Repository'
         run: >-
           aws ecr create-repository --repository-name ${{ env.REPOSITORY_NAME }}
