SkyU container Template Workflows Created

diff --git a/.github/workflows/container-dev_app_3da30b8_env_c6bda5f.yaml b/.github/workflows/container-dev_app_3da30b8_env_c6bda5f.yaml
--- a/.github/workflows/container-dev_app_3da30b8_env_c6bda5f.yaml
+++ b/.github/workflows/container-dev_app_3da30b8_env_c6bda5f.yaml
@@ -7,7 +7,7 @@ name: container-dev_app_3da30b8_env_c6bda5f Pipeline (Skyu Generated)
       - v*
   workflow_dispatch: {}
   repository_dispatch:
-    types: pipeline_fcc03b14-0c1a-43cc-a593-37395300fd81
+    types: pipeline_f38b0362-e8ea-4e76-a023-f6e55fc89479
 env:
   ENCODED_PIPELINE_SECRET: ${{secrets.TESTSERVICE2_CONTAINERDEV_APP_3DA30B8_ENV_C6BDA5F}}
   COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
@@ -44,17 +44,7 @@ jobs:
                   echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                 
       - name: Pipeline Started
-        run: |2-
-
-                context=$(echo -E '${{ toJson(github) }}' | jq 'del(.token)' || echo '{"run_id": "${{ github.run_id }}"}')
-                response=$(curl -X PUT -d "context=$context"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/PENDING')
-
-                if echo "$response" | grep -q '"success":true'; then
-                  echo "SUCCESS :: $response"
-                else
-                  echo "FAILED :: $response"
-                fi
-              
+        run: "\n      context=$(echo -E '${{ toJson(github) }}' | sed 's/[\x01-\x1F]//g' | jq 'del(.token)' || echo '{\"run_id\": \"${{ github.run_id }}\"}')\n      response=$(curl -X PUT -d \"context=$context\"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/PENDING')\n\n      if echo \"$response\" | grep -q '\"success\":true'; then\n        echo \"SUCCESS :: $response\"\n      else\n        echo \"FAILED :: $response\"\n      fi\n    "
   _release-info:
     name: _release Info
     permissions: write-all
@@ -266,11 +256,7 @@ jobs:
                   echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                 
       - name: Pipeline Success
-        run: |2-
-
-              context=$(echo -E '${{ toJson(github) }}' | jq 'del(.token)' || echo '{"run_id": "${{ github.run_id }}"}')
-              response=$(curl -X PUT -d "context=$context"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/SUCCESS')
-              
+        run: "\n    context=$(echo -E '${{ toJson(github) }}' | sed 's/[\x01-\x1F]//g' | jq 'del(.token)' || echo '{\"run_id\": \"${{ github.run_id }}\"}')\n    response=$(curl -X PUT -d \"context=$context\"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/SUCCESS')\n    "
   _status-failed:
     name: _status Failed
     permissions: write-all
@@ -290,11 +276,7 @@ jobs:
                   echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                 
       - name: Pipeline Failed
-        run: |2-
-
-              context=$(echo -E '${{ toJson(github) }}' | jq 'del(.token)' || echo '{"run_id": "${{ github.run_id }}"}')
-              response=$(curl -X PUT -d "context=$context"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/FAILED')
-              
+        run: "\n    context=$(echo -E '${{ toJson(github) }}' | sed 's/[\x01-\x1F]//g' | jq 'del(.token)' || echo '{\"run_id\": \"${{ github.run_id }}\"}')\n    response=$(curl -X PUT -d \"context=$context\"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/FAILED')\n    "
   deploy:
     name: Deploy
     permissions: write-all
