docker-helm-dev_app_e6745e6_env_43e64b6.yaml Created

diff --git a/.github/workflows/docker-helm-dev_app_e6745e6_env_43e64b6.yaml b/.github/workflows/docker-helm-dev_app_e6745e6_env_43e64b6.yaml
--- a/.github/workflows/docker-helm-dev_app_e6745e6_env_43e64b6.yaml
+++ b/.github/workflows/docker-helm-dev_app_e6745e6_env_43e64b6.yaml
@@ -2,7 +2,7 @@ name: docker-helm-dev_app_e6745e6_env_43e64b6 Pipeline (Skyu Generated)
 'on':
   workflow_dispatch: {}
   repository_dispatch:
-    types: pipeline_63fad669-420f-46c9-9574-ffd6be6fc9b9
+    types: pipeline_5a18a790-d090-4577-b791-b1fb5e26d008
 env:
   ENCODED_PIPELINE_SECRET: ${{secrets.TESTSERVICE2_DOCKERHELMDEV_APP_E6745E6_ENV_43E64B6}}
   COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
@@ -122,11 +122,41 @@ jobs:
                 echo "FAILED :: $response"
               fi
               
+  validate-helm-values:
+    name: Validate Helm Values
+    permissions: write-all
+    runs-on: ubuntu-latest
+    needs:
+      - _status-pending
+    steps:
+      - name: 'Run :: Decoding Secrets'
+        run: |2-
+
+                if [ ! -x "$(command -v jq)" ]; then
+                  echo "jq not found, installing..."
+                  sudo apt-get update
+                  sudo apt-get install -y jq
+                fi
+                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
+      - name: 'Run :: Validate Helm Update Values'
+        run: |2-
+
+              if [ -z "${{ github.event.client_payload.helmUpdateValues }}" ]; then
+                echo "Helm Update Values do not exist.";
+                exit 1;
+              else
+                echo "Helm Update Values: ${{ github.event.client_payload.helmUpdateValues }}";
+              fi
+              
+    outputs:
+      stepsCanProceed: ${{ env.STEPS_CAN_PROCEED }}
   build-and-push:
     name: Build And Push
     permissions: write-all
     runs-on: ubuntu-latest
     needs:
+      - validate-helm-values
       - _status-pending
     steps:
       - name: Start
@@ -176,16 +206,6 @@ jobs:
               else
                 echo "Image does not exist in registry."
                 echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
-              fi
-              
-      - name: 'Run :: Validate Helm Update Values'
-        run: |2-
-
-              if [ -z "${{ github.event.client_payload.helmUpdateValues }}" ]; then
-                echo "Helm Update Values do not exist.";
-                exit 1;
-              else
-                echo "Helm Update Values: ${{ github.event.client_payload.helmUpdateValues }}";
               fi
               
       - name: 'Run :: Build With Docker'
@@ -314,6 +334,7 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - code-scan
+      - validate-helm-values
       - build-and-push
       - helm-update
       - deploy
@@ -343,6 +364,7 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - code-scan
+      - validate-helm-values
       - build-and-push
       - helm-update
       - deploy
